"""domain email not null, position check constraint

Revision ID: 35740be99bf1
Revises: ee3731a66062
Create Date: 2026-02-14 00:40:18.763670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35740be99bf1'
down_revision: Union[str, Sequence[str], None] = 'ee3731a66062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'domain',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('people', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_check_constraint(
        'position_single_entity',
        'positions',
        "(CASE WHEN company_id IS NOT NULL THEN 1 ELSE 0 END"
        " + CASE WHEN pe_group_id IS NOT NULL THEN 1 ELSE 0 END"
        " + CASE WHEN industry_group_id IS NOT NULL THEN 1 ELSE 0 END) = 1",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('people', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('position_single_entity', 'positions')
    op.alter_column('companies', 'domain',
               existing_type=sa.VARCHAR(),
               nullable=True)
