"""add sales_rep hubspot and calendar tables

Revision ID: 5c8d71cd181e
Revises: a1b2c3d4e5f6
Create Date: 2026-02-17 21:29:06.884034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8d71cd181e'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_reps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hubspot_owner_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('hubspot_owner_id')
    )
    op.create_index(op.f('ix_sales_reps_id'), 'sales_reps', ['id'], unique=False)
    op.create_table('sales_rep_calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_rep_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('calendar_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['sales_reps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_rep_calendars_id'), 'sales_rep_calendars', ['id'], unique=False)
    op.add_column('companies', sa.Column('hubspot_company_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'companies', ['hubspot_company_id'])
    op.add_column('deals', sa.Column('name', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('hubspot_deal_id', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('hubspot_deal_stage', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('sales_rep_id', sa.Integer(), nullable=True))
    op.add_column('deals', sa.Column('close_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('deals', sa.Column('amount', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'deals', ['hubspot_deal_id'])
    op.create_foreign_key(None, 'deals', 'sales_reps', ['sales_rep_id'], ['id'])
    op.add_column('people', sa.Column('hubspot_contact_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'people', ['hubspot_contact_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'people', type_='unique')
    op.drop_column('people', 'hubspot_contact_id')
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_constraint(None, 'deals', type_='unique')
    op.drop_column('deals', 'amount')
    op.drop_column('deals', 'close_date')
    op.drop_column('deals', 'sales_rep_id')
    op.drop_column('deals', 'hubspot_deal_stage')
    op.drop_column('deals', 'hubspot_deal_id')
    op.drop_column('deals', 'name')
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'hubspot_company_id')
    op.drop_index(op.f('ix_sales_rep_calendars_id'), table_name='sales_rep_calendars')
    op.drop_table('sales_rep_calendars')
    op.drop_index(op.f('ix_sales_reps_id'), table_name='sales_reps')
    op.drop_table('sales_reps')
    # ### end Alembic commands ###
