"""add parent company

Revision ID: 93d06afdd234
Revises: c0fa4a1e38a1
Create Date: 2026-02-13 20:22:27.570134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d06afdd234'
down_revision: Union[str, Sequence[str], None] = 'c0fa4a1e38a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('parent_company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'companies', 'companies', ['parent_company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_column('companies', 'parent_company_id')
    # ### end Alembic commands ###
