"""website to domain, location to address, vertical enum

Revision ID: a3977a5c5b7a
Revises: cc63bee002b4
Create Date: 2026-02-13 20:06:18.007532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3977a5c5b7a'
down_revision: Union[str, Sequence[str], None] = 'cc63bee002b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    vertical_enum = sa.Enum(
        'BEARINGS', 'BUILDING_MATERIALS', 'ELECTRICAL', 'FASTENERS', 'FIRE_EQUIPMENT',
        'FLUID_POWER', 'FRAMING', 'GLASS', 'GYPSUM', 'HVAC', 'INDUSTRIAL_SUPPLY',
        'LUMBER', 'MEDICAL', 'MRO', 'OUTDOOR_SUPPLY', 'PACKAGING', 'PLUMBING',
        'POWER_TRANSMISSION', 'PVF', 'ROOFING', 'SAFETY_EQUIPMENT', 'TILING', 'TOOLS',
        'WIRE', name='vertical',
    )
    vertical_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('companies', sa.Column('domain', sa.String(), nullable=True))
    op.execute("ALTER TABLE companies ALTER COLUMN vertical TYPE vertical USING vertical::vertical")
    op.drop_column('companies', 'website')

    op.add_column('events', sa.Column('address', sa.String(), nullable=True))
    op.drop_column('events', 'location')

    op.add_column('industry_groups', sa.Column('domain', sa.String(), nullable=True))
    op.execute("ALTER TABLE industry_groups ALTER COLUMN vertical TYPE vertical USING vertical::vertical")
    op.drop_column('industry_groups', 'website')

    op.add_column('pe_groups', sa.Column('domain', sa.String(), nullable=True))
    op.drop_column('pe_groups', 'website')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pe_groups', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pe_groups', 'domain')
    op.add_column('industry_groups', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('industry_groups', 'vertical',
               existing_type=sa.Enum('BEARINGS', 'BUILDING_MATERIALS', 'ELECTRICAL', 'FASTENERS', 'FIRE_EQUIPMENT', 'FLUID_POWER', 'FRAMING', 'GLASS', 'GYPSUM', 'HVAC', 'INDUSTRIAL_SUPPLY', 'LUMBER', 'MEDICAL', 'MRO', 'OUTDOOR_SUPPLY', 'PACKAGING', 'PLUMBING', 'POWER_TRANSMISSION', 'PVF', 'ROOFING', 'SAFETY_EQUIPMENT', 'TILING', 'TOOLS', 'WIRE', name='vertical'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('industry_groups', 'domain')
    op.add_column('events', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('events', 'address')
    op.add_column('companies', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('companies', 'vertical',
               existing_type=sa.Enum('BEARINGS', 'BUILDING_MATERIALS', 'ELECTRICAL', 'FASTENERS', 'FIRE_EQUIPMENT', 'FLUID_POWER', 'FRAMING', 'GLASS', 'GYPSUM', 'HVAC', 'INDUSTRIAL_SUPPLY', 'LUMBER', 'MEDICAL', 'MRO', 'OUTDOOR_SUPPLY', 'PACKAGING', 'PLUMBING', 'POWER_TRANSMISSION', 'PVF', 'ROOFING', 'SAFETY_EQUIPMENT', 'TILING', 'TOOLS', 'WIRE', name='vertical'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('companies', 'domain')
    # ### end Alembic commands ###
