"""industry_group domain nullable

Revision ID: af3909eb22e0
Revises: cacf6b07e401
Create Date: 2026-02-14 02:38:44.432011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af3909eb22e0'
down_revision: Union[str, Sequence[str], None] = 'cacf6b07e401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('industry_groups', 'domain',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('industry_groups', 'domain',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
