"""unique domain constraint

Revision ID: c0fa4a1e38a1
Revises: a3977a5c5b7a
Create Date: 2026-02-13 20:17:54.145403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0fa4a1e38a1'
down_revision: Union[str, Sequence[str], None] = 'a3977a5c5b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'companies', ['domain'])
    op.create_unique_constraint(None, 'industry_groups', ['domain'])
    op.create_unique_constraint(None, 'pe_groups', ['domain'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pe_groups', type_='unique')
    op.drop_constraint(None, 'industry_groups', type_='unique')
    op.drop_constraint(None, 'companies', type_='unique')
    # ### end Alembic commands ###
