"""pe_group and industry_group domain not null

Revision ID: cacf6b07e401
Revises: 97a4e4d3796a
Create Date: 2026-02-14 02:27:50.168164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cacf6b07e401'
down_revision: Union[str, Sequence[str], None] = '97a4e4d3796a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clean up rows with NULL domains and their dependents
    op.execute(
        "DELETE FROM positions WHERE industry_group_id IN "
        "(SELECT id FROM industry_groups WHERE domain IS NULL)"
    )
    op.execute(
        "DELETE FROM company_industry_group WHERE industry_group_id IN "
        "(SELECT id FROM industry_groups WHERE domain IS NULL)"
    )
    op.execute("DELETE FROM industry_groups WHERE domain IS NULL")

    op.execute(
        "DELETE FROM positions WHERE pe_group_id IN "
        "(SELECT id FROM pe_groups WHERE domain IS NULL)"
    )
    op.execute(
        "DELETE FROM pe_group_company WHERE pe_group_id IN "
        "(SELECT id FROM pe_groups WHERE domain IS NULL)"
    )
    op.execute("DELETE FROM pe_groups WHERE domain IS NULL")

    op.alter_column('industry_groups', 'domain',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pe_groups', 'domain',
               existing_type=sa.VARCHAR(),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pe_groups', 'domain',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('industry_groups', 'domain',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
