"""email auth and single industry group m2m

Revision ID: cc63bee002b4
Revises: 1ed33d2753f0
Create Date: 2026-02-13 19:56:45.087471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc63bee002b4'
down_revision: Union[str, Sequence[str], None] = '1ed33d2753f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_industry_group',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('industry_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['industry_group_id'], ['industry_groups.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'industry_group_id')
    )
    op.drop_table('company_conference')
    op.drop_table('company_association')
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'email')
    op.create_table('company_association',
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('industry_group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('company_association_company_id_fkey')),
    sa.ForeignKeyConstraint(['industry_group_id'], ['industry_groups.id'], name=op.f('company_association_industry_group_id_fkey')),
    sa.PrimaryKeyConstraint('company_id', 'industry_group_id', name=op.f('company_association_pkey'))
    )
    op.create_table('company_conference',
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('industry_group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('company_conference_company_id_fkey')),
    sa.ForeignKeyConstraint(['industry_group_id'], ['industry_groups.id'], name=op.f('company_conference_industry_group_id_fkey')),
    sa.PrimaryKeyConstraint('company_id', 'industry_group_id', name=op.f('company_conference_pkey'))
    )
    op.drop_table('company_industry_group')
    # ### end Alembic commands ###
