"""add role enum to positions

Revision ID: fea6a0707be8
Revises: bf56c27bcf47
Create Date: 2026-02-13 21:45:00.571337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea6a0707be8'
down_revision: Union[str, Sequence[str], None] = 'bf56c27bcf47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    role_enum = sa.Enum('CEO', 'CIO', 'CCO', 'COO', 'PRESIDENT', 'OTHER_C_SUITE', 'VP_LEVEL', 'OTHER', name='role')
    role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('positions', sa.Column('role', role_enum, nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'role')
    # ### end Alembic commands ###
